name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download and Extract Liquibase
        run: |
          sudo mkdir -p liquibase && sudo chown -R runner:docker liquibase
          cd liquibase
          wget -q https://github.com/liquibase/liquibase/releases/download/v4.25.0/liquibase-4.25.0.tar.gz
          tar -xzf liquibase-4.25.0.tar.gz
          mkdir -p lib

      - name: Download Snowflake JDBC Driver
        run: |
          cd liquibase
          wget -q https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.14.5/snowflake-jdbc-3.14.5.jar
          mv snowflake-jdbc-3.14.5.jar lib/

      - name: Verify SQL File Exists
        run: |
          find /home/runner/work/LiquibaseDeployment/LiquibaseDeployment/dbscripts -type f -name "*.sql"

   
