name: Deploy to Snowflake

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Download and Extract Liquibase
        run: |
          sudo mkdir -p liquibase
          sudo chown -R runner:docker liquibase
          cd liquibase
          wget -q https://github.com/liquibase/liquibase/releases/download/v4.25.0/liquibase-4.25.0.tar.gz
          tar -xzf liquibase-4.25.0.tar.gz

      - name: Create lib directory for drivers
        run: |
          cd liquibase
          mkdir -p lib

      - name: Download Snowflake JDBC Driver
        run: |
          cd liquibase
          wget -q https://repo1.maven.org/maven2/net/snowflake/snowflake-jdbc/3.14.5/snowflake-jdbc-3.14.5.jar
          mv snowflake-jdbc-3.14.5.jar lib/

      - name: Run Liquibase Update (Log Output)
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          mkdir -p logs
          cd liquibase
          ./liquibase --search-path=/home/runner/work/LiquibaseDeployment/LiquibaseDeployment/dbscripts update \
          --changelog-file=change2.sql \
          --username=${{ secrets.SNOWFLAKE_USER }} \
          --password=${{ secrets.SNOWFLAKE_PASSWORD }} \
          --classpath=lib/snowflake-jdbc-3.14.5.jar \
          --url='jdbc:snowflake://WXVXDID-ZN02370.snowflakecomputing.com/?db=${{ secrets.SNOWFLAKE_DATABASE }}&schema=${{ secrets.SNOWFLAKE_SCHEMA }}&warehouse=COMPUTE_WH' \
          --driver='net.snowflake.client.jdbc.SnowflakeDriver' \
          --log-level=debug > ../logs/liquibase-update.log 2>&1

      - name: Run Liquibase Rollback (Log Output)
        env:
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          cd liquibase
          ./liquibase --search-path=/home/runner/work/LiquibaseDeployment/LiquibaseDeployment/dbscripts rollbackCount 1 \
          --changelog-file=change2.sql \
          --username=${{ secrets.SNOWFLAKE_USER }} \
          --password=${{ secrets.SNOWFLAKE_PASSWORD }} \
          --classpath=lib/snowflake-jdbc-3.14.5.jar \
          --url='jdbc:snowflake://WXVXDID-ZN02370.snowflakecomputing.com/?db=${{ secrets.SNOWFLAKE_DATABASE }}&schema=${{ secrets.SNOWFLAKE_SCHEMA }}&warehouse=COMPUTE_WH' \
          --driver='net.snowflake.client.jdbc.SnowflakeDriver' \
          --log-level=debug > ../logs/liquibase-rollback.log 2>&1

      - name: Upload Liquibase Logs
        uses: actions/upload-artifact@v4
        with:
          name: liquibase-logs
          path: logs/
